name: Build and deploy Node.js app to Azure Web App - celeste-internal

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js version
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Step 3: Install dependencies and build
      - name: Install dependencies
        run: npm install
      
      # Step 4: Upload build artifacts
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: |
            . 

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
    permissions:
      id-token: write # Required for OIDC authentication

    steps:
      # Step 1: Download build artifact
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      # Step 2: Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_d6eb518b-d809-4de6-b9fc-42049e525c34 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9626b467-07d8-493a-a4d3-3a30be8524c9 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_78520e8d-9136-4c84-85fb-89b0e819bc8a }}

      # Step 3: Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'celeste-internal'
          package: . # Point to the artifact location or specific deployment folder
